

[MeasureImage0]
Measure=Plugin
Plugin=WebParser
UpdateRate=10000000000000
Download=1
Debug=1

[MeterBackground0]
Meter=Image
MouseOverAction=[!SetOption MeterBackground0 SolidColor #colorOptionShow#][!Update]
MouseLeaveAction=[!SetOption MeterBackground0 SolidColor #transparent#][!Update]
[MeterStreamTitle0]
Meter=String
MeterStyle=styleSubTitle
[MeterStreamGame0]
Meter=String
MeterStyle=styleText
[MeterStreamViewers0]
Meter=String
MeterStyle=styleText
[MeterImage0]
Meter=Image
MeasureName=MeasureImage0
[MeterSidebar0]
Meter=Image
MouseOverAction=[!SetOption MeterSidebar0 SolidColor #colorOptionShow#][!Update]
MouseLeaveAction=[!SetOption MeterSidebar0 SolidColor #transparent#][!Update]
LeftMouseUpAction=[!CommandMeasure MainScript ExpandRow(0)][!Update]
[MeterChevronDown0]
Meter=Image
ImageName=#@#Images\Chevron_Down.png
Hidden=1
[MeterChevronUp0]
Meter=Image
ImageName=#@#Images\Chevron_Up.png
Hidden=1
[MeterDetails0]
Meter=String
MeterStyle=styleDetails
[MeterDivider0]
Meter=Image
SolidColor=#dividerColor#


[MeasureImage1]
Measure=Plugin
Plugin=WebParser
UpdateRate=10000000000000
Download=1
Debug=1

[MeterBackground1]
Meter=Image
MouseOverAction=[!SetOption MeterBackground1 SolidColor #colorOptionShow#][!Update]
MouseLeaveAction=[!SetOption MeterBackground1 SolidColor #transparent#][!Update]
[MeterStreamTitle1]
Meter=String
MeterStyle=styleSubTitle
[MeterStreamGame1]
Meter=String
MeterStyle=styleText
[MeterStreamViewers1]
Meter=String
MeterStyle=styleText
[MeterImage1]
Meter=Image
MeasureName=MeasureImage1
[MeterSidebar1]
Meter=Image
MouseOverAction=[!SetOption MeterSidebar1 SolidColor #colorOptionShow#][!Update]
MouseLeaveAction=[!SetOption MeterSidebar1 SolidColor #transparent#][!Update]
LeftMouseUpAction=[!CommandMeasure MainScript ExpandRow(1)][!Update]
[MeterChevronDown1]
Meter=Image
ImageName=#@#Images\Chevron_Down.png
Hidden=1
[MeterChevronUp1]
Meter=Image
ImageName=#@#Images\Chevron_Up.png
Hidden=1
[MeterDetails1]
Meter=String
MeterStyle=styleDetails
[MeterDivider1]
Meter=Image
SolidColor=#dividerColor#


[MeasureImage2]
Measure=Plugin
Plugin=WebParser
UpdateRate=10000000000000
Download=1
Debug=1

[MeterBackground2]
Meter=Image
MouseOverAction=[!SetOption MeterBackground2 SolidColor #colorOptionShow#][!Update]
MouseLeaveAction=[!SetOption MeterBackground2 SolidColor #transparent#][!Update]
[MeterStreamTitle2]
Meter=String
MeterStyle=styleSubTitle
[MeterStreamGame2]
Meter=String
MeterStyle=styleText
[MeterStreamViewers2]
Meter=String
MeterStyle=styleText
[MeterImage2]
Meter=Image
MeasureName=MeasureImage2
[MeterSidebar2]
Meter=Image
MouseOverAction=[!SetOption MeterSidebar2 SolidColor #colorOptionShow#][!Update]
MouseLeaveAction=[!SetOption MeterSidebar2 SolidColor #transparent#][!Update]
LeftMouseUpAction=[!CommandMeasure MainScript ExpandRow(2)][!Update]
[MeterChevronDown2]
Meter=Image
ImageName=#@#Images\Chevron_Down.png
Hidden=1
[MeterChevronUp2]
Meter=Image
ImageName=#@#Images\Chevron_Up.png
Hidden=1
[MeterDetails2]
Meter=String
MeterStyle=styleDetails
[MeterDivider2]
Meter=Image
SolidColor=#dividerColor#


[MeasureImage3]
Measure=Plugin
Plugin=WebParser
UpdateRate=10000000000000
Download=1
Debug=1

[MeterBackground3]
Meter=Image
MouseOverAction=[!SetOption MeterBackground3 SolidColor #colorOptionShow#][!Update]
MouseLeaveAction=[!SetOption MeterBackground3 SolidColor #transparent#][!Update]
[MeterStreamTitle3]
Meter=String
MeterStyle=styleSubTitle
[MeterStreamGame3]
Meter=String
MeterStyle=styleText
[MeterStreamViewers3]
Meter=String
MeterStyle=styleText
[MeterImage3]
Meter=Image
MeasureName=MeasureImage3
[MeterSidebar3]
Meter=Image
MouseOverAction=[!SetOption MeterSidebar3 SolidColor #colorOptionShow#][!Update]
MouseLeaveAction=[!SetOption MeterSidebar3 SolidColor #transparent#][!Update]
LeftMouseUpAction=[!CommandMeasure MainScript ExpandRow(3)][!Update]
[MeterChevronDown3]
Meter=Image
ImageName=#@#Images\Chevron_Down.png
Hidden=1
[MeterChevronUp3]
Meter=Image
ImageName=#@#Images\Chevron_Up.png
Hidden=1
[MeterDetails3]
Meter=String
MeterStyle=styleDetails
[MeterDivider3]
Meter=Image
SolidColor=#dividerColor#


[MeasureImage4]
Measure=Plugin
Plugin=WebParser
UpdateRate=10000000000000
Download=1
Debug=1

[MeterBackground4]
Meter=Image
MouseOverAction=[!SetOption MeterBackground4 SolidColor #colorOptionShow#][!Update]
MouseLeaveAction=[!SetOption MeterBackground4 SolidColor #transparent#][!Update]
[MeterStreamTitle4]
Meter=String
MeterStyle=styleSubTitle
[MeterStreamGame4]
Meter=String
MeterStyle=styleText
[MeterStreamViewers4]
Meter=String
MeterStyle=styleText
[MeterImage4]
Meter=Image
MeasureName=MeasureImage4
[MeterSidebar4]
Meter=Image
MouseOverAction=[!SetOption MeterSidebar4 SolidColor #colorOptionShow#][!Update]
MouseLeaveAction=[!SetOption MeterSidebar4 SolidColor #transparent#][!Update]
LeftMouseUpAction=[!CommandMeasure MainScript ExpandRow(4)][!Update]
[MeterChevronDown4]
Meter=Image
ImageName=#@#Images\Chevron_Down.png
Hidden=1
[MeterChevronUp4]
Meter=Image
ImageName=#@#Images\Chevron_Up.png
Hidden=1
[MeterDetails4]
Meter=String
MeterStyle=styleDetails
[MeterDivider4]
Meter=Image
SolidColor=#dividerColor#


[MeasureImage5]
Measure=Plugin
Plugin=WebParser
UpdateRate=10000000000000
Download=1
Debug=1

[MeterBackground5]
Meter=Image
MouseOverAction=[!SetOption MeterBackground5 SolidColor #colorOptionShow#][!Update]
MouseLeaveAction=[!SetOption MeterBackground5 SolidColor #transparent#][!Update]
[MeterStreamTitle5]
Meter=String
MeterStyle=styleSubTitle
[MeterStreamGame5]
Meter=String
MeterStyle=styleText
[MeterStreamViewers5]
Meter=String
MeterStyle=styleText
[MeterImage5]
Meter=Image
MeasureName=MeasureImage5
[MeterSidebar5]
Meter=Image
MouseOverAction=[!SetOption MeterSidebar5 SolidColor #colorOptionShow#][!Update]
MouseLeaveAction=[!SetOption MeterSidebar5 SolidColor #transparent#][!Update]
LeftMouseUpAction=[!CommandMeasure MainScript ExpandRow(5)][!Update]
[MeterChevronDown5]
Meter=Image
ImageName=#@#Images\Chevron_Down.png
Hidden=1
[MeterChevronUp5]
Meter=Image
ImageName=#@#Images\Chevron_Up.png
Hidden=1
[MeterDetails5]
Meter=String
MeterStyle=styleDetails
[MeterDivider5]
Meter=Image
SolidColor=#dividerColor#


[MeasureImage6]
Measure=Plugin
Plugin=WebParser
UpdateRate=10000000000000
Download=1
Debug=1

[MeterBackground6]
Meter=Image
MouseOverAction=[!SetOption MeterBackground6 SolidColor #colorOptionShow#][!Update]
MouseLeaveAction=[!SetOption MeterBackground6 SolidColor #transparent#][!Update]
[MeterStreamTitle6]
Meter=String
MeterStyle=styleSubTitle
[MeterStreamGame6]
Meter=String
MeterStyle=styleText
[MeterStreamViewers6]
Meter=String
MeterStyle=styleText
[MeterImage6]
Meter=Image
MeasureName=MeasureImage6
[MeterSidebar6]
Meter=Image
MouseOverAction=[!SetOption MeterSidebar6 SolidColor #colorOptionShow#][!Update]
MouseLeaveAction=[!SetOption MeterSidebar6 SolidColor #transparent#][!Update]
LeftMouseUpAction=[!CommandMeasure MainScript ExpandRow(6)][!Update]
[MeterChevronDown6]
Meter=Image
ImageName=#@#Images\Chevron_Down.png
Hidden=1
[MeterChevronUp6]
Meter=Image
ImageName=#@#Images\Chevron_Up.png
Hidden=1
[MeterDetails6]
Meter=String
MeterStyle=styleDetails
[MeterDivider6]
Meter=Image
SolidColor=#dividerColor#


[MeasureImage7]
Measure=Plugin
Plugin=WebParser
UpdateRate=10000000000000
Download=1
Debug=1

[MeterBackground7]
Meter=Image
MouseOverAction=[!SetOption MeterBackground7 SolidColor #colorOptionShow#][!Update]
MouseLeaveAction=[!SetOption MeterBackground7 SolidColor #transparent#][!Update]
[MeterStreamTitle7]
Meter=String
MeterStyle=styleSubTitle
[MeterStreamGame7]
Meter=String
MeterStyle=styleText
[MeterStreamViewers7]
Meter=String
MeterStyle=styleText
[MeterImage7]
Meter=Image
MeasureName=MeasureImage7
[MeterSidebar7]
Meter=Image
MouseOverAction=[!SetOption MeterSidebar7 SolidColor #colorOptionShow#][!Update]
MouseLeaveAction=[!SetOption MeterSidebar7 SolidColor #transparent#][!Update]
LeftMouseUpAction=[!CommandMeasure MainScript ExpandRow(7)][!Update]
[MeterChevronDown7]
Meter=Image
ImageName=#@#Images\Chevron_Down.png
Hidden=1
[MeterChevronUp7]
Meter=Image
ImageName=#@#Images\Chevron_Up.png
Hidden=1
[MeterDetails7]
Meter=String
MeterStyle=styleDetails
[MeterDivider7]
Meter=Image
SolidColor=#dividerColor#


[MeasureImage8]
Measure=Plugin
Plugin=WebParser
UpdateRate=10000000000000
Download=1
Debug=1

[MeterBackground8]
Meter=Image
MouseOverAction=[!SetOption MeterBackground8 SolidColor #colorOptionShow#][!Update]
MouseLeaveAction=[!SetOption MeterBackground8 SolidColor #transparent#][!Update]
[MeterStreamTitle8]
Meter=String
MeterStyle=styleSubTitle
[MeterStreamGame8]
Meter=String
MeterStyle=styleText
[MeterStreamViewers8]
Meter=String
MeterStyle=styleText
[MeterImage8]
Meter=Image
MeasureName=MeasureImage8
[MeterSidebar8]
Meter=Image
MouseOverAction=[!SetOption MeterSidebar8 SolidColor #colorOptionShow#][!Update]
MouseLeaveAction=[!SetOption MeterSidebar8 SolidColor #transparent#][!Update]
LeftMouseUpAction=[!CommandMeasure MainScript ExpandRow(8)][!Update]
[MeterChevronDown8]
Meter=Image
ImageName=#@#Images\Chevron_Down.png
Hidden=1
[MeterChevronUp8]
Meter=Image
ImageName=#@#Images\Chevron_Up.png
Hidden=1
[MeterDetails8]
Meter=String
MeterStyle=styleDetails
[MeterDivider8]
Meter=Image
SolidColor=#dividerColor#


[MeasureImage9]
Measure=Plugin
Plugin=WebParser
UpdateRate=10000000000000
Download=1
Debug=1

[MeterBackground9]
Meter=Image
MouseOverAction=[!SetOption MeterBackground9 SolidColor #colorOptionShow#][!Update]
MouseLeaveAction=[!SetOption MeterBackground9 SolidColor #transparent#][!Update]
[MeterStreamTitle9]
Meter=String
MeterStyle=styleSubTitle
[MeterStreamGame9]
Meter=String
MeterStyle=styleText
[MeterStreamViewers9]
Meter=String
MeterStyle=styleText
[MeterImage9]
Meter=Image
MeasureName=MeasureImage9
[MeterSidebar9]
Meter=Image
MouseOverAction=[!SetOption MeterSidebar9 SolidColor #colorOptionShow#][!Update]
MouseLeaveAction=[!SetOption MeterSidebar9 SolidColor #transparent#][!Update]
LeftMouseUpAction=[!CommandMeasure MainScript ExpandRow(9)][!Update]
[MeterChevronDown9]
Meter=Image
ImageName=#@#Images\Chevron_Down.png
Hidden=1
[MeterChevronUp9]
Meter=Image
ImageName=#@#Images\Chevron_Up.png
Hidden=1
[MeterDetails9]
Meter=String
MeterStyle=styleDetails
[MeterDivider9]
Meter=Image
SolidColor=#dividerColor#


[MeasureImage10]
Measure=Plugin
Plugin=WebParser
UpdateRate=10000000000000
Download=1
Debug=1

[MeterBackground10]
Meter=Image
MouseOverAction=[!SetOption MeterBackground10 SolidColor #colorOptionShow#][!Update]
MouseLeaveAction=[!SetOption MeterBackground10 SolidColor #transparent#][!Update]
[MeterStreamTitle10]
Meter=String
MeterStyle=styleSubTitle
[MeterStreamGame10]
Meter=String
MeterStyle=styleText
[MeterStreamViewers10]
Meter=String
MeterStyle=styleText
[MeterImage10]
Meter=Image
MeasureName=MeasureImage10
[MeterSidebar10]
Meter=Image
MouseOverAction=[!SetOption MeterSidebar10 SolidColor #colorOptionShow#][!Update]
MouseLeaveAction=[!SetOption MeterSidebar10 SolidColor #transparent#][!Update]
LeftMouseUpAction=[!CommandMeasure MainScript ExpandRow(10)][!Update]
[MeterChevronDown10]
Meter=Image
ImageName=#@#Images\Chevron_Down.png
Hidden=1
[MeterChevronUp10]
Meter=Image
ImageName=#@#Images\Chevron_Up.png
Hidden=1
[MeterDetails10]
Meter=String
MeterStyle=styleDetails
[MeterDivider10]
Meter=Image
SolidColor=#dividerColor#


[MeasureImage11]
Measure=Plugin
Plugin=WebParser
UpdateRate=10000000000000
Download=1
Debug=1

[MeterBackground11]
Meter=Image
MouseOverAction=[!SetOption MeterBackground11 SolidColor #colorOptionShow#][!Update]
MouseLeaveAction=[!SetOption MeterBackground11 SolidColor #transparent#][!Update]
[MeterStreamTitle11]
Meter=String
MeterStyle=styleSubTitle
[MeterStreamGame11]
Meter=String
MeterStyle=styleText
[MeterStreamViewers11]
Meter=String
MeterStyle=styleText
[MeterImage11]
Meter=Image
MeasureName=MeasureImage11
[MeterSidebar11]
Meter=Image
MouseOverAction=[!SetOption MeterSidebar11 SolidColor #colorOptionShow#][!Update]
MouseLeaveAction=[!SetOption MeterSidebar11 SolidColor #transparent#][!Update]
LeftMouseUpAction=[!CommandMeasure MainScript ExpandRow(11)][!Update]
[MeterChevronDown11]
Meter=Image
ImageName=#@#Images\Chevron_Down.png
Hidden=1
[MeterChevronUp11]
Meter=Image
ImageName=#@#Images\Chevron_Up.png
Hidden=1
[MeterDetails11]
Meter=String
MeterStyle=styleDetails
[MeterDivider11]
Meter=Image
SolidColor=#dividerColor#


[MeasureImage12]
Measure=Plugin
Plugin=WebParser
UpdateRate=10000000000000
Download=1
Debug=1

[MeterBackground12]
Meter=Image
MouseOverAction=[!SetOption MeterBackground12 SolidColor #colorOptionShow#][!Update]
MouseLeaveAction=[!SetOption MeterBackground12 SolidColor #transparent#][!Update]
[MeterStreamTitle12]
Meter=String
MeterStyle=styleSubTitle
[MeterStreamGame12]
Meter=String
MeterStyle=styleText
[MeterStreamViewers12]
Meter=String
MeterStyle=styleText
[MeterImage12]
Meter=Image
MeasureName=MeasureImage12
[MeterSidebar12]
Meter=Image
MouseOverAction=[!SetOption MeterSidebar12 SolidColor #colorOptionShow#][!Update]
MouseLeaveAction=[!SetOption MeterSidebar12 SolidColor #transparent#][!Update]
LeftMouseUpAction=[!CommandMeasure MainScript ExpandRow(12)][!Update]
[MeterChevronDown12]
Meter=Image
ImageName=#@#Images\Chevron_Down.png
Hidden=1
[MeterChevronUp12]
Meter=Image
ImageName=#@#Images\Chevron_Up.png
Hidden=1
[MeterDetails12]
Meter=String
MeterStyle=styleDetails
[MeterDivider12]
Meter=Image
SolidColor=#dividerColor#


[MeasureImage13]
Measure=Plugin
Plugin=WebParser
UpdateRate=10000000000000
Download=1
Debug=1

[MeterBackground13]
Meter=Image
MouseOverAction=[!SetOption MeterBackground13 SolidColor #colorOptionShow#][!Update]
MouseLeaveAction=[!SetOption MeterBackground13 SolidColor #transparent#][!Update]
[MeterStreamTitle13]
Meter=String
MeterStyle=styleSubTitle
[MeterStreamGame13]
Meter=String
MeterStyle=styleText
[MeterStreamViewers13]
Meter=String
MeterStyle=styleText
[MeterImage13]
Meter=Image
MeasureName=MeasureImage13
[MeterSidebar13]
Meter=Image
MouseOverAction=[!SetOption MeterSidebar13 SolidColor #colorOptionShow#][!Update]
MouseLeaveAction=[!SetOption MeterSidebar13 SolidColor #transparent#][!Update]
LeftMouseUpAction=[!CommandMeasure MainScript ExpandRow(13)][!Update]
[MeterChevronDown13]
Meter=Image
ImageName=#@#Images\Chevron_Down.png
Hidden=1
[MeterChevronUp13]
Meter=Image
ImageName=#@#Images\Chevron_Up.png
Hidden=1
[MeterDetails13]
Meter=String
MeterStyle=styleDetails
[MeterDivider13]
Meter=Image
SolidColor=#dividerColor#


[MeasureImage14]
Measure=Plugin
Plugin=WebParser
UpdateRate=10000000000000
Download=1
Debug=1

[MeterBackground14]
Meter=Image
MouseOverAction=[!SetOption MeterBackground14 SolidColor #colorOptionShow#][!Update]
MouseLeaveAction=[!SetOption MeterBackground14 SolidColor #transparent#][!Update]
[MeterStreamTitle14]
Meter=String
MeterStyle=styleSubTitle
[MeterStreamGame14]
Meter=String
MeterStyle=styleText
[MeterStreamViewers14]
Meter=String
MeterStyle=styleText
[MeterImage14]
Meter=Image
MeasureName=MeasureImage14
[MeterSidebar14]
Meter=Image
MouseOverAction=[!SetOption MeterSidebar14 SolidColor #colorOptionShow#][!Update]
MouseLeaveAction=[!SetOption MeterSidebar14 SolidColor #transparent#][!Update]
LeftMouseUpAction=[!CommandMeasure MainScript ExpandRow(14)][!Update]
[MeterChevronDown14]
Meter=Image
ImageName=#@#Images\Chevron_Down.png
Hidden=1
[MeterChevronUp14]
Meter=Image
ImageName=#@#Images\Chevron_Up.png
Hidden=1
[MeterDetails14]
Meter=String
MeterStyle=styleDetails
[MeterDivider14]
Meter=Image
SolidColor=#dividerColor#


[MeasureImage15]
Measure=Plugin
Plugin=WebParser
UpdateRate=10000000000000
Download=1
Debug=1

[MeterBackground15]
Meter=Image
MouseOverAction=[!SetOption MeterBackground15 SolidColor #colorOptionShow#][!Update]
MouseLeaveAction=[!SetOption MeterBackground15 SolidColor #transparent#][!Update]
[MeterStreamTitle15]
Meter=String
MeterStyle=styleSubTitle
[MeterStreamGame15]
Meter=String
MeterStyle=styleText
[MeterStreamViewers15]
Meter=String
MeterStyle=styleText
[MeterImage15]
Meter=Image
MeasureName=MeasureImage15
[MeterSidebar15]
Meter=Image
MouseOverAction=[!SetOption MeterSidebar15 SolidColor #colorOptionShow#][!Update]
MouseLeaveAction=[!SetOption MeterSidebar15 SolidColor #transparent#][!Update]
LeftMouseUpAction=[!CommandMeasure MainScript ExpandRow(15)][!Update]
[MeterChevronDown15]
Meter=Image
ImageName=#@#Images\Chevron_Down.png
Hidden=1
[MeterChevronUp15]
Meter=Image
ImageName=#@#Images\Chevron_Up.png
Hidden=1
[MeterDetails15]
Meter=String
MeterStyle=styleDetails
[MeterDivider15]
Meter=Image
SolidColor=#dividerColor#


[MeasureImage16]
Measure=Plugin
Plugin=WebParser
UpdateRate=10000000000000
Download=1
Debug=1

[MeterBackground16]
Meter=Image
MouseOverAction=[!SetOption MeterBackground16 SolidColor #colorOptionShow#][!Update]
MouseLeaveAction=[!SetOption MeterBackground16 SolidColor #transparent#][!Update]
[MeterStreamTitle16]
Meter=String
MeterStyle=styleSubTitle
[MeterStreamGame16]
Meter=String
MeterStyle=styleText
[MeterStreamViewers16]
Meter=String
MeterStyle=styleText
[MeterImage16]
Meter=Image
MeasureName=MeasureImage16
[MeterSidebar16]
Meter=Image
MouseOverAction=[!SetOption MeterSidebar16 SolidColor #colorOptionShow#][!Update]
MouseLeaveAction=[!SetOption MeterSidebar16 SolidColor #transparent#][!Update]
LeftMouseUpAction=[!CommandMeasure MainScript ExpandRow(16)][!Update]
[MeterChevronDown16]
Meter=Image
ImageName=#@#Images\Chevron_Down.png
Hidden=1
[MeterChevronUp16]
Meter=Image
ImageName=#@#Images\Chevron_Up.png
Hidden=1
[MeterDetails16]
Meter=String
MeterStyle=styleDetails
[MeterDivider16]
Meter=Image
SolidColor=#dividerColor#


[MeasureImage17]
Measure=Plugin
Plugin=WebParser
UpdateRate=10000000000000
Download=1
Debug=1

[MeterBackground17]
Meter=Image
MouseOverAction=[!SetOption MeterBackground17 SolidColor #colorOptionShow#][!Update]
MouseLeaveAction=[!SetOption MeterBackground17 SolidColor #transparent#][!Update]
[MeterStreamTitle17]
Meter=String
MeterStyle=styleSubTitle
[MeterStreamGame17]
Meter=String
MeterStyle=styleText
[MeterStreamViewers17]
Meter=String
MeterStyle=styleText
[MeterImage17]
Meter=Image
MeasureName=MeasureImage17
[MeterSidebar17]
Meter=Image
MouseOverAction=[!SetOption MeterSidebar17 SolidColor #colorOptionShow#][!Update]
MouseLeaveAction=[!SetOption MeterSidebar17 SolidColor #transparent#][!Update]
LeftMouseUpAction=[!CommandMeasure MainScript ExpandRow(17)][!Update]
[MeterChevronDown17]
Meter=Image
ImageName=#@#Images\Chevron_Down.png
Hidden=1
[MeterChevronUp17]
Meter=Image
ImageName=#@#Images\Chevron_Up.png
Hidden=1
[MeterDetails17]
Meter=String
MeterStyle=styleDetails
[MeterDivider17]
Meter=Image
SolidColor=#dividerColor#


[MeasureImage18]
Measure=Plugin
Plugin=WebParser
UpdateRate=10000000000000
Download=1
Debug=1

[MeterBackground18]
Meter=Image
MouseOverAction=[!SetOption MeterBackground18 SolidColor #colorOptionShow#][!Update]
MouseLeaveAction=[!SetOption MeterBackground18 SolidColor #transparent#][!Update]
[MeterStreamTitle18]
Meter=String
MeterStyle=styleSubTitle
[MeterStreamGame18]
Meter=String
MeterStyle=styleText
[MeterStreamViewers18]
Meter=String
MeterStyle=styleText
[MeterImage18]
Meter=Image
MeasureName=MeasureImage18
[MeterSidebar18]
Meter=Image
MouseOverAction=[!SetOption MeterSidebar18 SolidColor #colorOptionShow#][!Update]
MouseLeaveAction=[!SetOption MeterSidebar18 SolidColor #transparent#][!Update]
LeftMouseUpAction=[!CommandMeasure MainScript ExpandRow(18)][!Update]
[MeterChevronDown18]
Meter=Image
ImageName=#@#Images\Chevron_Down.png
Hidden=1
[MeterChevronUp18]
Meter=Image
ImageName=#@#Images\Chevron_Up.png
Hidden=1
[MeterDetails18]
Meter=String
MeterStyle=styleDetails
[MeterDivider18]
Meter=Image
SolidColor=#dividerColor#


[MeasureImage19]
Measure=Plugin
Plugin=WebParser
UpdateRate=10000000000000
Download=1
Debug=1

[MeterBackground19]
Meter=Image
MouseOverAction=[!SetOption MeterBackground19 SolidColor #colorOptionShow#][!Update]
MouseLeaveAction=[!SetOption MeterBackground19 SolidColor #transparent#][!Update]
[MeterStreamTitle19]
Meter=String
MeterStyle=styleSubTitle
[MeterStreamGame19]
Meter=String
MeterStyle=styleText
[MeterStreamViewers19]
Meter=String
MeterStyle=styleText
[MeterImage19]
Meter=Image
MeasureName=MeasureImage19
[MeterSidebar19]
Meter=Image
MouseOverAction=[!SetOption MeterSidebar19 SolidColor #colorOptionShow#][!Update]
MouseLeaveAction=[!SetOption MeterSidebar19 SolidColor #transparent#][!Update]
LeftMouseUpAction=[!CommandMeasure MainScript ExpandRow(19)][!Update]
[MeterChevronDown19]
Meter=Image
ImageName=#@#Images\Chevron_Down.png
Hidden=1
[MeterChevronUp19]
Meter=Image
ImageName=#@#Images\Chevron_Up.png
Hidden=1
[MeterDetails19]
Meter=String
MeterStyle=styleDetails
[MeterDivider19]
Meter=Image
SolidColor=#dividerColor#


[MeasureImage20]
Measure=Plugin
Plugin=WebParser
UpdateRate=10000000000000
Download=1
Debug=1

[MeterBackground20]
Meter=Image
MouseOverAction=[!SetOption MeterBackground20 SolidColor #colorOptionShow#][!Update]
MouseLeaveAction=[!SetOption MeterBackground20 SolidColor #transparent#][!Update]
[MeterStreamTitle20]
Meter=String
MeterStyle=styleSubTitle
[MeterStreamGame20]
Meter=String
MeterStyle=styleText
[MeterStreamViewers20]
Meter=String
MeterStyle=styleText
[MeterImage20]
Meter=Image
MeasureName=MeasureImage20
[MeterSidebar20]
Meter=Image
MouseOverAction=[!SetOption MeterSidebar20 SolidColor #colorOptionShow#][!Update]
MouseLeaveAction=[!SetOption MeterSidebar20 SolidColor #transparent#][!Update]
LeftMouseUpAction=[!CommandMeasure MainScript ExpandRow(20)][!Update]
[MeterChevronDown20]
Meter=Image
ImageName=#@#Images\Chevron_Down.png
Hidden=1
[MeterChevronUp20]
Meter=Image
ImageName=#@#Images\Chevron_Up.png
Hidden=1
[MeterDetails20]
Meter=String
MeterStyle=styleDetails
[MeterDivider20]
Meter=Image
SolidColor=#dividerColor#
