; -- Measures

[MeasureImage0]
Measure=Plugin
Plugin=WebParser
UpdateRate=10000000000000
Download=1
[MeasureImage1]
Measure=Plugin
Plugin=WebParser
UpdateRate=10000000000000
Download=1
[MeasureImage2]
Measure=Plugin
Plugin=WebParser
UpdateRate=10000000000000
Download=1
[MeasureImage3]
Measure=Plugin
Plugin=WebParser
UpdateRate=10000000000000
Download=1
[MeasureImage4]
Measure=Plugin
Plugin=WebParser
UpdateRate=10000000000000
Download=1
[MeasureImage5]
Measure=Plugin
Plugin=WebParser
UpdateRate=10000000000000
Download=1
[MeasureImage6]
Measure=Plugin
Plugin=WebParser
UpdateRate=10000000000000
Download=1
[MeasureImage7]
Measure=Plugin
Plugin=WebParser
UpdateRate=10000000000000
Download=1
[MeasureImage8]
Measure=Plugin
Plugin=WebParser
UpdateRate=10000000000000
Download=1
[MeasureImage9]
Measure=Plugin
Plugin=WebParser
UpdateRate=10000000000000
Download=1

;-- Streams

[MeterBackground0]
Meter=Image
MouseOverAction=!SetOption MeterBackground0 SolidColor #colorOptionShow#
MouseLeaveAction=!SetOption MeterBackground0 SolidColor #transparent#
[MeterStreamTitle0]
Meter=String
MeterStyle=styleSubTitle
[MeterStreamGame0]
Meter=String
MeterStyle=styleText
[MeterStreamViewers0]
Meter=String
MeterStyle=styleText
[MeterImage0]
Meter=Image
MeasureName=MeasureImage0
[MeterSidebar0]
Meter=Image
MouseOverAction=!SetOption MeterSidebar0 SolidColor #colorOptionShow#
MouseLeaveAction=!SetOption MeterSidebar0 SolidColor #transparent#
LeftMouseUpAction=!CommandMeasure MainScript ExpandRow(0)
[MeterChevronDown0]
Meter=Image
ImageName=#@#Images\Chevron_Down.png
[MeterChevronUp0]
Meter=Image
ImageName=#@#Images\Chevron_Up.png
[MeterDetails0]
Meter=String
MeterStyle=styleDetails
[MeterDivider0]
Meter=Image
SolidColor=#dividerColor#

[MeterBackground1]
Meter=Image
MouseOverAction=!SetOption MeterBackground1 SolidColor #colorOptionShow#
MouseLeaveAction=!SetOption MeterBackground1 SolidColor #transparent#
[MeterStreamTitle1]
Meter=String
MeterStyle=styleSubTitle
[MeterStreamGame1]
Meter=String
MeterStyle=styleText
[MeterStreamViewers1]
Meter=String
MeterStyle=styleText
[MeterImage1]
Meter=Image
MeasureName=MeasureImage1
[MeterSidebar1]
Meter=Image
MouseOverAction=!SetOption MeterSidebar1 SolidColor #colorOptionShow#
MouseLeaveAction=!SetOption MeterSidebar1 SolidColor #transparent#
LeftMouseUpAction=!CommandMeasure MainScript ExpandRow(1)
[MeterChevronDown1]
Meter=Image
ImageName=#@#Images\Chevron_Down.png
[MeterChevronUp1]
Meter=Image
ImageName=#@#Images\Chevron_Up.png
[MeterDetails1]
Meter=String
MeterStyle=styleDetails
[MeterDivider1]
Meter=Image
SolidColor=#dividerColor#

[MeterBackground2]
Meter=Image
MouseOverAction=!SetOption MeterBackground2 SolidColor #colorOptionShow#
MouseLeaveAction=!SetOption MeterBackground2 SolidColor #transparent#
[MeterStreamTitle2]
Meter=String
MeterStyle=styleSubTitle
[MeterStreamGame2]
Meter=String
MeterStyle=styleText
[MeterStreamViewers2]
Meter=String
MeterStyle=styleText
[MeterImage2]
Meter=Image
MeasureName=MeasureImage2
[MeterSidebar2]
Meter=Image
MouseOverAction=!SetOption MeterSidebar2 SolidColor #colorOptionShow#
MouseLeaveAction=!SetOption MeterSidebar2 SolidColor #transparent#
LeftMouseUpAction=!CommandMeasure MainScript ExpandRow(2)
[MeterChevronDown2]
Meter=Image
ImageName=#@#Images\Chevron_Down.png
[MeterChevronUp2]
Meter=Image
ImageName=#@#Images\Chevron_Up.png
[MeterDetails2]
Meter=String
MeterStyle=styleDetails
[MeterDivider2]
Meter=Image
SolidColor=#dividerColor#

[MeterBackground3]
Meter=Image
MouseOverAction=!SetOption MeterBackground3 SolidColor #colorOptionShow#
MouseLeaveAction=!SetOption MeterBackground3 SolidColor #transparent#
[MeterStreamTitle3]
Meter=String
MeterStyle=styleSubTitle
[MeterStreamGame3]
Meter=String
MeterStyle=styleText
[MeterStreamViewers3]
Meter=String
MeterStyle=styleText
[MeterImage3]
Meter=Image
MeasureName=MeasureImage3
[MeterSidebar3]
Meter=Image
MouseOverAction=!SetOption MeterSidebar3 SolidColor #colorOptionShow#
MouseLeaveAction=!SetOption MeterSidebar3 SolidColor #transparent#
LeftMouseUpAction=!CommandMeasure MainScript ExpandRow(3)
[MeterChevronDown3]
Meter=Image
ImageName=#@#Images\Chevron_Down.png
[MeterChevronUp3]
Meter=Image
ImageName=#@#Images\Chevron_Up.png
[MeterDetails3]
Meter=String
MeterStyle=styleDetails
[MeterDivider3]
Meter=Image
SolidColor=#dividerColor#

[MeterBackground4]
Meter=Image
MouseOverAction=!SetOption MeterBackground4 SolidColor #colorOptionShow#
MouseLeaveAction=!SetOption MeterBackground4 SolidColor #transparent#
[MeterStreamTitle4]
Meter=String
MeterStyle=styleSubTitle
[MeterStreamGame4]
Meter=String
MeterStyle=styleText
[MeterStreamViewers4]
Meter=String
MeterStyle=styleText
[MeterImage4]
Meter=Image
MeasureName=MeasureImage4
[MeterSidebar4]
Meter=Image
MouseOverAction=!SetOption MeterSidebar4 SolidColor #colorOptionShow#
MouseLeaveAction=!SetOption MeterSidebar4 SolidColor #transparent#
LeftMouseUpAction=!CommandMeasure MainScript ExpandRow(4)
[MeterChevronDown4]
Meter=Image
ImageName=#@#Images\Chevron_Down.png
[MeterChevronUp4]
Meter=Image
ImageName=#@#Images\Chevron_Up.png
[MeterDetails4]
Meter=String
MeterStyle=styleDetails
[MeterDivider4]
Meter=Image
SolidColor=#dividerColor#

[MeterBackground5]
Meter=Image
MouseOverAction=!SetOption MeterBackground5 SolidColor #colorOptionShow#
MouseLeaveAction=!SetOption MeterBackground5 SolidColor #transparent#
[MeterStreamTitle5]
Meter=String
MeterStyle=styleSubTitle
[MeterStreamGame5]
Meter=String
MeterStyle=styleText
[MeterStreamViewers5]
Meter=String
MeterStyle=styleText
[MeterImage5]
Meter=Image
MeasureName=MeasureImage5
[MeterSidebar5]
Meter=Image
MouseOverAction=!SetOption MeterSidebar5 SolidColor #colorOptionShow#
MouseLeaveAction=!SetOption MeterSidebar5 SolidColor #transparent#
LeftMouseUpAction=!CommandMeasure MainScript ExpandRow(5)
[MeterChevronDown5]
Meter=Image
ImageName=#@#Images\Chevron_Down.png
[MeterChevronUp5]
Meter=Image
ImageName=#@#Images\Chevron_Up.png
[MeterDetails5]
Meter=String
MeterStyle=styleDetails
[MeterDivider5]
Meter=Image
SolidColor=#dividerColor#

[MeterBackground6]
Meter=Image
MouseOverAction=!SetOption MeterBackground6 SolidColor #colorOptionShow#
MouseLeaveAction=!SetOption MeterBackground6 SolidColor #transparent#
[MeterStreamTitle6]
Meter=String
MeterStyle=styleSubTitle
[MeterStreamGame6]
Meter=String
MeterStyle=styleText
[MeterStreamViewers6]
Meter=String
MeterStyle=styleText
[MeterImage6]
Meter=Image
MeasureName=MeasureImage6
[MeterSidebar6]
Meter=Image
MouseOverAction=!SetOption MeterSidebar6 SolidColor #colorOptionShow#
MouseLeaveAction=!SetOption MeterSidebar6 SolidColor #transparent#
LeftMouseUpAction=!CommandMeasure MainScript ExpandRow(6)
[MeterChevronDown6]
Meter=Image
ImageName=#@#Images\Chevron_Down.png
[MeterChevronUp6]
Meter=Image
ImageName=#@#Images\Chevron_Up.png
[MeterDetails6]
Meter=String
MeterStyle=styleDetails
[MeterDivider6]
Meter=Image
SolidColor=#dividerColor#

[MeterBackground7]
Meter=Image
MouseOverAction=!SetOption MeterBackground7 SolidColor #colorOptionShow#
MouseLeaveAction=!SetOption MeterBackground7 SolidColor #transparent#
[MeterStreamTitle7]
Meter=String
MeterStyle=styleSubTitle
[MeterStreamGame7]
Meter=String
MeterStyle=styleText
[MeterStreamViewers7]
Meter=String
MeterStyle=styleText
[MeterImage7]
Meter=Image
MeasureName=MeasureImage7
[MeterSidebar7]
Meter=Image
MouseOverAction=!SetOption MeterSidebar7 SolidColor #colorOptionShow#
MouseLeaveAction=!SetOption MeterSidebar7 SolidColor #transparent#
LeftMouseUpAction=!CommandMeasure MainScript ExpandRow(7)
[MeterChevronDown7]
Meter=Image
ImageName=#@#Images\Chevron_Down.png
[MeterChevronUp7]
Meter=Image
ImageName=#@#Images\Chevron_Up.png
[MeterDetails7]
Meter=String
MeterStyle=styleDetails
[MeterDivider7]
Meter=Image
SolidColor=#dividerColor#

[MeterBackground8]
Meter=Image
MouseOverAction=!SetOption MeterBackground8 SolidColor #colorOptionShow#
MouseLeaveAction=!SetOption MeterBackground8 SolidColor #transparent#
[MeterStreamTitle8]
Meter=String
MeterStyle=styleSubTitle
[MeterStreamGame8]
Meter=String
MeterStyle=styleText
[MeterStreamViewers8]
Meter=String
MeterStyle=styleText
[MeterImage8]
Meter=Image
MeasureName=MeasureImage8
[MeterSidebar8]
Meter=Image
MouseOverAction=!SetOption MeterSidebar8 SolidColor #colorOptionShow#
MouseLeaveAction=!SetOption MeterSidebar8 SolidColor #transparent#
LeftMouseUpAction=!CommandMeasure MainScript ExpandRow(8)
[MeterChevronDown8]
Meter=Image
ImageName=#@#Images\Chevron_Down.png
[MeterChevronUp8]
Meter=Image
ImageName=#@#Images\Chevron_Up.png
[MeterDetails8]
Meter=String
MeterStyle=styleDetails
[MeterDivider8]
Meter=Image
SolidColor=#dividerColor#


[MeterBackground9]
Meter=Image
MouseOverAction=!SetOption MeterBackground9 SolidColor #colorOptionShow#
MouseLeaveAction=!SetOption MeterBackground9 SolidColor #transparent#
[MeterStreamTitle9]
Meter=String
MeterStyle=styleSubTitle
[MeterStreamGame9]
Meter=String
MeterStyle=styleText
[MeterStreamViewers9]
Meter=String
MeterStyle=styleText
[MeterImage9]
Meter=Image
MeasureName=MeasureImage9
[MeterSidebar9]
Meter=Image
MouseOverAction=!SetOption MeterSidebar9 SolidColor #colorOptionShow#
MouseLeaveAction=!SetOption MeterSidebar9 SolidColor #transparent#
LeftMouseUpAction=!CommandMeasure MainScript ExpandRow(9)
[MeterChevronDown9]
Meter=Image
ImageName=#@#Images\Chevron_Down.png
[MeterChevronUp9]
Meter=Image
ImageName=#@#Images\Chevron_Up.png
[MeterDetails9]
Meter=String
MeterStyle=styleDetails
[MeterDivider9]
Meter=Image
SolidColor=#dividerColor#