[Variables]
width=325
fontName=Roboto
textSize=8
transparent=0,0,0,0

; Grey
;colorOptionShow=80,80,80
;backgroundColor=29,35,45
;dividerColor=50,50,50

; Blue
;colorText=184,181,192
;colorOptionShow=32,28,43
;backgroundColor=23,20,31,200
;dividerColor=60,60,60

; colorText=0,0,0
; colorHeaderText=230,226,175
; headerColor=0,47,47
; colorOptionShow=239,236,202
; backgroundColor=239,236,202,90
; dividerColor=60,60,60

; headerColor=25,52,65
; colorHeaderText=252,255,245
; colorText=252,255,245
; backgroundColor=62,96,111,90
; colorOptionShow=25,52,65,200
; dividerColor=145,170,157,90

headercolor=0,0,0,1
colorheadertext=252,255,245
colortext=252,255,245
backgroundcolor=0,0,0,1
coloroptionshow=25,52,65,200
dividercolor=255,255,255,90


[styleTitle]
StringAlign=Center
StringEffect=Shadow
FontEffectColor=0,0,0,50
FontColor=#colorHeaderText#
FontFace=#fontName#
FontSize=13
AntiAlias=1
ClipString=1

[styleSubTitle]
StringStyle=Bold
FontEffectColor=0,0,0,50
FontColor=#colorText#
FontFace=#fontName#
FontSize=10
AntiAlias=1
ClipString=1

[styleText]
FontColor=#colorText#
FontFace=#fontName#
FontSize=10
AntiAlias=1
ClipString=1

[styleDetails]
FontColor=#colorText#
FontFace=#fontName#
FontSize=9
AntiAlias=1
ClipString=1

[styleFooter]
StringAlign=Right
FontColor=#colorText#
FontFace=#fontName#
FontSize=8
AntiAlias=1
ClipString=1