[Variables]
width=325
textSize=8
transparent=0,0,0,0

@Include=#@#/Styles/StarWars.inc

[styleTitle]
StringAlign=Center
StringStyle=Bold
StringEffect=Shadow
FontEffectColor=0,0,0,50
FontColor=#colorHeaderText#
FontFace=#titleFontName#
FontSize=20
AntiAlias=1
ClipString=1

[styleSubTitle]
StringStyle=Bold
FontEffectColor=0,0,0,50
FontColor=#colorText#
FontFace=#fontName#
FontSize=10
AntiAlias=1
ClipString=1

[styleText]
FontColor=#colorText#
FontFace=#fontName#
FontSize=9
AntiAlias=1
ClipString=1

[styleDetails]
FontColor=#colorText#
FontFace=#fontName#
FontSize=9
AntiAlias=1
ClipString=1

[styleFooter]
StringAlign=Right
FontColor=#colorText#
FontFace=#fontName#
FontSize=8
AntiAlias=1
ClipString=1