[styleGraphTitle]
StringAlign=Center
FontColor=255,255,255
[styleXLabels]
StringAlign=Center
FontColor=255,255,255
[styleYLabels]
StringAlign=Left
FontColor=255,255,255
[Variables]
StrokeColor=255,138,0,255


[MeterGraphTitle]
Meter=String
MeterStyle=styleGraphTitle
[MeterBackground]
Meter=Image
[MeterAxisX]
Meter=Shape
[MeterAxisY]
Meter=Shape
[MeterGraphData]
Meter=Shape

[MeterLabelY0]
Meter=String
MeterStyle=styleYLabels
[MeterLabelY1]
Meter=String
MeterStyle=styleYLabels
[MeterLabelY2]
Meter=String
MeterStyle=styleYLabels
[MeterLabelY3]
Meter=String
MeterStyle=styleYLabels
[MeterLabelY4]
Meter=String
MeterStyle=styleYLabels
[MeterLabelY5]
Meter=String
MeterStyle=styleYLabels
[MeterLabelY6]
Meter=String
MeterStyle=styleYLabels
[MeterLabelY7]
Meter=String
MeterStyle=styleYLabels

[MeterLineY0]
Meter=Shape
[MeterLineY1]
Meter=Shape
[MeterLineY2]
Meter=Shape
[MeterLineY3]
Meter=Shape
[MeterLineY4]
Meter=Shape
[MeterLineY5]
Meter=Shape
[MeterLineY6]
Meter=Shape
[MeterLineY7]
Meter=Shape



[MeterLabelX0]
Meter=String
MeterStyle=styleXLabels
[MeterLabelX1]
Meter=String
MeterStyle=styleXLabels
[MeterLabelX2]
Meter=String
MeterStyle=styleXLabels
[MeterLabelX3]
Meter=String
MeterStyle=styleXLabels
[MeterLabelX4]
Meter=String
MeterStyle=styleXLabels
[MeterLabelX5]
Meter=String
MeterStyle=styleXLabels
[MeterLabelX6]
Meter=String
MeterStyle=styleXLabels
[MeterLabelX7]
Meter=String
MeterStyle=styleXLabels

[MeterLineX0]
Meter=Shape
[MeterLineX1]
Meter=Shape
[MeterLineX2]
Meter=Shape
[MeterLineX3]
Meter=Shape
[MeterLineX4]
Meter=Shape
[MeterLineX5]
Meter=Shape
[MeterLineX6]
Meter=Shape
[MeterLineX7]
Meter=Shape


[MeterPoint0]
Meter=Shape
Shape=Ellipse 0,0,5 | Fill Color #StrokeColor#
Hidden=1
[MeterPointTrigger0]
Meter=Image
SolidColor=0,0,0,1
W=10
H=10
MouseOverAction=[!ShowMeter MeterPoint0][!Update]
MouseLeaveAction=[!HideMeter MeterPoint0][!Update]

[MeterPoint1]
Meter=Shape
Shape=Ellipse 0,0,5 | Fill Color #StrokeColor#
Hidden=1
[MeterPointTrigger1]
Meter=Image
SolidColor=0,0,0,1
W=10
H=10
MouseOverAction=[!ShowMeter MeterPoint1][!Update]
MouseLeaveAction=[!HideMeter MeterPoint1][!Update]

[MeterPoint2]
Meter=Shape
Shape=Ellipse 0,0,5 | Fill Color #StrokeColor#
Hidden=1
[MeterPointTrigger2]
Meter=Image
SolidColor=0,0,0,1
W=10
H=10
MouseOverAction=[!ShowMeter MeterPoint2][!Update]
MouseLeaveAction=[!HideMeter MeterPoint2][!Update]

[MeterPoint3]
Meter=Shape
Shape=Ellipse 0,0,5 | Fill Color #StrokeColor#
Hidden=1
[MeterPointTrigger3]
Meter=Image
SolidColor=0,0,0,1
W=10
H=10
MouseOverAction=[!ShowMeter MeterPoint3][!Update]
MouseLeaveAction=[!HideMeter MeterPoint3][!Update]

[MeterPoint4]
Meter=Shape
Shape=Ellipse 0,0,5 | Fill Color #StrokeColor#
Hidden=1
[MeterPointTrigger4]
Meter=Image
SolidColor=0,0,0,1
W=10
H=10
MouseOverAction=[!ShowMeter MeterPoint4][!Update]
MouseLeaveAction=[!HideMeter MeterPoint4][!Update]

[MeterPoint5]
Meter=Shape
Shape=Ellipse 0,0,5 | Fill Color #StrokeColor#
Hidden=1
[MeterPointTrigger5]
Meter=Image
SolidColor=0,0,0,1
W=10
H=10
MouseOverAction=[!ShowMeter MeterPoint5][!Update]
MouseLeaveAction=[!HideMeter MeterPoint5][!Update]

[MeterPoint6]
Meter=Shape
Shape=Ellipse 0,0,5 | Fill Color #StrokeColor#
Hidden=1
[MeterPointTrigger6]
Meter=Image
SolidColor=0,0,0,1
W=10
H=10
MouseOverAction=[!ShowMeter MeterPoint6][!Update]
MouseLeaveAction=[!HideMeter MeterPoint6][!Update]

[MeterPoint7]
Meter=Shape
Shape=Ellipse 0,0,5 | Fill Color #StrokeColor#
Hidden=1
[MeterPointTrigger7]
Meter=Image
SolidColor=0,0,0,1
W=10
H=10
MouseOverAction=[!ShowMeter MeterPoint7][!Update]
MouseLeaveAction=[!HideMeter MeterPoint7][!Update]
